fix(next): withPayload wrapper next.js 16 support (#14473)
Next.js 16 throws the following error:

```ts
 ERROR: This build is using Turbopack, with a `webpack` config and no `turbopack` config.
   This may be a mistake.

   As of Next.js 16 Turbopack is enabled by default and
   custom webpack configurations may need to be migrated to Turbopack.

   NOTE: your `webpack` config may have been added by a configuration plugin.

   To configure Turbopack, see https://nextjs.org/docs/app/api-reference/next-config-js/turbopack

   TIP: Many applications work fine under Turbopack with no configuration,
   if that is the case for you, you can silence this error by passing the
   `--turbopack` or `--webpack` flag explicitly or simply setting an 
   empty turbopack config in your Next config file (e.g. `turbopack: {}`).
```

This PR fixes this error by adding a turbopack property to our next.js
config wrapper.